
#http://www.sthda.com/english/wiki/correspondence-analysis-in-r-the-ultimate-guide-for-the-analysis-the-visualization-and-the-interpretation-r-software-and-data-mining

library("FactoMineR")
library("factoextra")

data(housetasks)
housetasks

library("gplots")

library("graphics")

dt <- as.table(as.matrix(housetasks))
mosaicplot(dt, shade = TRUE, las=2,
           main = "housetasks")

par(mfrow=c(1,1), mar=c(4,4,3,3))
mosaicplot(m, shade = TRUE, main = "X vs Y")

library("vcd")
# plot just a subset of the table
assoc(dt, shade = T, las=3)
assoc(m, shade = T, las=3)

#Test de Independencia. 
chisq <- chisq.test(housetasks)
chisq


chisq <- chisq.test(m)
chisq

#Análisis de Correspondencia.
CA(m, ncp = 5, graph = TRUE)

p <- CA(m, ncp = 5, graph = FALSE)
p$col$coord
p$row$coord
xmin = min(p$row$coord[,1], p$col$coord[,1])[1] * 1.1
xmax = max(p$row$coord[,1], p$col$coord[,1])[1] * 1.1
ymin = min(p$row$coord[,2], p$col$coord[,2])[1] * 1.1
ymax = max(p$row$coord[,2], p$col$coord[,2])[1] * 1.1
plot(p$row$coord, c(0,0,0), type = "p", pch = 16, col="blue",
     xlim=c(-0.013*1.3, 0.013*1.3),
     ylim=c(-0.012*1.1, 0.012*1.1),
     xlab="Dimensión 1", ylab="Dimensión 2",
     main = "X vs Z", cex.main=0.7
     )
points(p$col$coord, c(0,0), type = "p", pch = 17, col="red")
for (i in 1:nrow(m)) {
  text(p$row$coord[i], 0.005, rownames(m)[i], col="blue", cex=0.6)
}
for (i in 1:ncol(m)) {
  text(p$col$coord[i], -0.005, colnames(m)[i], col="red", cex=0.6)
}
abline(h=0,lty=2)
abline(v=0,lty=2) 

#name              description                   
#1  "$eig"            "eigenvalues"                 
#2  "$col"            "results for the columns"     
#3  "$col$coord"      "coord. for the columns"      
#4  "$col$cos2"       "cos2 for the columns"        
#5  "$col$contrib"    "contributions of the columns"
#6  "$row"            "results for the rows"        
#7  "$row$coord"      "coord. for the rows"         
#8  "$row$cos2"       "cos2 for the rows"           
#9  "$row$contrib"    "contributions of the rows"   
#10 "$call"           "summary called parameters"   
#11 "$call$marge.col" "weights of the columns"      
#12 "$call$marge.row" "weights of the rows"

p$eig
summary(p)


#Interpretation of CA outputs

#Significance of the association between rows and columns
#To interpret correspondence analysis, the first step is to evaluate whether there is a significant dependency between the rows and columns.

#There are two methods to inspect the significance:
  
#  Using the trace
#The trace is the the total inertia of the table (i.e, the sum of the eigenvalues). 
#The square root of the trace is interpreted as the correlation coefficient between rows and columns.

#The correlation coefficient is calculated as follow:
  
eig <- get_eigenvalue(p)
trace <- sum(eig$eigenvalue) 
cor.coef <- sqrt(trace)
cor.coef

#Note that, as a rule of thumb 0.2 is the threshold above which the correlation can be considered as 
#important (Bendixen 1995, 576; Healey 2013, 289-290).

#Using the Chi-square statistic
#A more rigorous method is to use the chi-square statistic for examining the association. 
#This appears at the top of the report generated by the function summary.CA().
#A high chi-square statistic means strong link between row and column variables.

#Note that, the chi-square statistics = trace * n, where n is the grand total of the table 
#(total frequency); see the R code below:
# Chi-square statistics
chi2 <- trace*sum(m)
chi2

# Degree of freedom
df <- (nrow(m) - 1) * (ncol(m) - 1)
# P-value
pval <- pchisq(chi2, df = df, lower.tail = FALSE)
pval

eigenvalues <- get_eigenvalue(p)
head(round(eigenvalues, 2))

fviz_screeplot(p)

fviz_screeplot(p) +
  geom_hline(yintercept=33.33, linetype=2, color="red")

library("corrplot")
corrplot(p$row$contrib, is.corr=FALSE)

# Contributions of rows on Dim.1
fviz_contrib(p, choice = "row", axes = 1)
fviz_contrib(p, choice = "row", axes = 1:2)


#Symmetric biplot
#As mentioned above, the standard plot of correspondence analysis is a symmetric biplot in which both rows 
#(blue points) and columns (red triangles) are represented in the same space using the principal coordinates. 
#These coordinates represent the row and column profiles. In this case, only the distance between row points 
#or the distance between column points can be really interpreted.

#With symmetric plot, the inter-distance between rows and columns can’t be interpreted. Only a general 
#statements can be made about the pattern.

#Note that, in order to interpret the distance between column points and row points, the simplest way is 
#to make an asymmetric plot (Bendixen, 2003). This means that, the column profiles must be presented in 
#row space or vice-versa.

#To make an asymetric plot, rows (or columns) points are plotted from the standard co-ordinates (S) and the 
#profiles of the columns (or the rows) are plotted from the principale coordinates (P) (Bendixen 2003).

fviz_ca_biplot()
p1 <- fviz_ca_biplot(p, map ="symbiplot", arrow = c(TRUE, TRUE))
plot(p1)

#If the angle between two arrows is acute, then their is a strong association between the corresponding row 
#and column.

#To interpret the distance between rows and a column you should perpendicularly project row points on 
#the column arrow.

fviz_ca_biplot(p, map ="rowgreen",
               arrow = c(FALSE, TRUE))

fviz_ca_biplot(p, map ="colgab",
               arrow = c(FALSE, TRUE))

fviz_ca_row(p)

dimdesc(p, axes = 1:2, proba = 0.05)



data(mtcars)
y <- xtabs( ~ mtcars$cyl + mtcars$gear + mtcars$vs)
y <- xtabs( ~ mtcars$cyl + mtcars$gear)
y



mat <- readMat(file.path(origenMat, fichero_ruido))
df <- as.data.frame(cbind(as.vector(mat$x), as.vector(mat$y), as.vector(mat$z)))
colnames(df) <- c("old_x", "y", "z")
df <- cbind(df, rep(as.character("[0, 11)"), length(df$y)))
colnames(df)[4] <- "x"
df$x <- as.character(df$x)
df[df$old_x >= 11 & df$old_x < 25, "x"] <- "[11, 25)"
df[df$old_x >= 25 & df$old_x <= 40, "x"] <- "[25, 40]"
df$x <- factor(df$x)
suppressMessages(a <- sqldf("select x, z, count(*) as total from df group by x, z"))
m <- getMatrizfromDF(a)
